### ISSUE TITLE
Create an interface that enforces predictable operator names for the Decodable stream sources and sinks

### ISSUE THREAD

**Issue by maxf-decodable** [decodableco/decodable-pipeline-sdk#42]
* Currently, the Decodable stream sources and sinks, when inserted into a `DataStream` graph, are arbitrarily nameable. This presents issues for the Decodable platform when attempting to correlate runtime metrics from the graph operators back to the referenced streams.

**Comment by nicoweidner** [comment]
@maxf-decodable Is this issue done?

**Comment by maxf-decodable** [comment]
Done-ish. https://github.com/decodableco/decodable-pipeline-sdk/pull/44 merged to suggest this scheme of operator naming instead of https://github.com/decodableco/decodable-pipeline-sdk/pull/41 to enforce it.
